'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu
    
    '''<summary>
    '''divMove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMove As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkMove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkMove As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divCycleCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCycleCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkCycleCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkCycleCount As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divJobMatlTran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJobMatlTran As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkJobMatlTran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkJobMatlTran As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divUnposted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnposted As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkUnposted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUnposted As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divJobReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJobReceipt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkJobReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkJobReceipt As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divOrderShipping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrderShipping As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkOrderShipping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkOrderShipping As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divGenerateGRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGenerateGRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkGenerateGRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkGenerateGRN As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divMissOper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMissOper As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkMissOper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkMissOper As Global.System.Web.UI.WebControls.HyperLink
End Class
